### ISSUE TITLE
PR list is not complete

### ISSUE THREAD

**Issue by resouer** [nikhita/github-contrib#1]
I have `Total Pull Requests Created: 125`, it's right.

But only 50 of them are listed in the report, is it by design or a bug?

**Comment by nikhita** [comment]
@resouer Thanks for the feedback! I had set the number of PRs to be displayed as 50 so that it did not make everything cluttered. But I guess it makes sense to remove that restriction. Will update it! :+1:

**Comment by resouer** [comment]
Or configurable, it's depends on you anyway, thank you! Will close this.
