### ISSUE TITLE
rate limit exceeded even using token

### ISSUE THREAD

**Issue by mbacchi** [nikhita/github-contrib#2]
I get rate limit exceeded when running the command:

```
./bin/github-contrib -token=XXXX eucalyptus mbacchi

GET https://api.github.com/search/issues?per_page=50&q=is%3Apr+repo%3Aeucalyptus%2Ffaststart+reviewed-by%3Ambacchi: 403 API rate limit exceeded for mbacchi. [rate limit was reset 0s ago]
```
It appears the sleepIfRateLimitExceeded isn't returning the time to sleep properly. I'll dig into this some more myself but I'm also new to Go :-)

**Comment by nikhita** [comment]
@mbacchi thanks for reporting the issue! Oops, that should not happen. :)

I can check this over the weekend (also plan to fix + add a few things). :+1:

**Comment by nikhita** [comment]
This occurred because `sleepIfRateLimitExceeded` did not sleep if the rate limit was reset 0 seconds back. It is fixed now. Closing.
